version: '3.6'

services:
  server:
    env_file: "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - 5000:5000

  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client
    ports:
       - 3000:3000