version: '3.6'

services:
  server:
    env_file: "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - 5000:5000

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client
    ports:
      - 3000:3000

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "issue-certificate:1:1,:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
